apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      app: tomcat-demo
  template:
    metadata:
      labels:
        app: tomcat-demo
    spec:
      imagePullSecrets:
      - name: SECRET_NAME
      containers:
      - name: tomcat1
        image: IMAGE_NAME
      resources:
        requests:
          cpu: 0.2
          memory: 250Mi
        limits:
          cpu: 1
          memory: 1Gi
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat-demo
  type: NodePort
